AWSTemplateFormatVersion: '2010-09-09'
Description: >
  S3 buckets for Terraform remote state with logging bucket and proper security.

Parameters:
  Environment:
    Type: String
    Description: Environment name (e.g. dev, prod)
    AllowedPattern: "^[a-z0-9-]+$"
    Default: dev
  
  StateBucket:
    Type: String
    Description: Name of the S3 bucket for Terraform state

Resources:

  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${StateBucket}-${Environment}"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  StateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${StateBucket}-${Environment}"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket
        LogFilePrefix: !Sub "${Environment}/access-logs/"
