AWSTemplateFormatVersion: '2010-09-09'
Description: >
  S3 buckets for Terraform remote state with logging bucket and proper security.

Parameters:
  Environment:
    Type: String
    Description: Environment name (e.g. dev, prod)
    AllowedPattern: "^[a-z0-9-]+$"
    Default: dev
  
  StateBucketNamePrefix:
    Type: String
    Description: Prefix for the S3 bucket names (e.g. "peex-habid-softserve")

Resources:

  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${StateBucketNamePrefix}-logs-${Environment}"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  StateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${StateBucketNamePrefix}-tfstate-${Environment}"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket
        LogFilePrefix: !Sub "${Environment}/access-logs/"

Outputs:
  StateBucketName:
    Description: "Terraform state bucket name"
    Value: !Ref StateBucket

  LogBucketName:
    Description: "Logging bucket name"
    Value: !Ref LogBucket
